import { Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const recursive = Recursive({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={recursive.className}>
      <main className='flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]'>
          <div className='flex-1 flex flex-col h-full'>
          <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
